### ISSUE TITLE
[Windows 10] ERROR: No supported platform found in manifest list

### ISSUE THREAD

**Issue by MrDoctorJ** [yannbertrand/apple-watch-workouts-year-review#1]
Error when running `docker-compose up -d`. 

`Pulling influxdb (influxdb:1.7)...
1.7: Pulling from library/influxdb
ERROR: no supported platform found in manifest list`

**Comment by yannbertrand** [comment]
Hey!

Unfortunately it seems that the influxdb image I'm using doesn't work with Windows container. You should be able to switch to Linux containers tho. Can you take a look at https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers?

**Comment by MrDoctorJ** [comment]
Hey that worked. Thanks for your help.
